// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 5.maintenance_events.sql

package sqlc

import (
	"context"
)

const deleteMaintenanceEvent = `-- name: DeleteMaintenanceEvent :exec
DELETE FROM maintenance_events WHERE id = $1
`

func (q *Queries) DeleteMaintenanceEvent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMaintenanceEvent, id)
	return err
}

const listMaintenanceByDevice = `-- name: ListMaintenanceByDevice :many
SELECT id, device_id, at, interval, notes, performed_by, cost, created_at FROM maintenance_events
WHERE device_id = $1
ORDER BY at DESC
LIMIT $2 OFFSET $3
`

type ListMaintenanceByDeviceParams struct {
	DeviceID int64 `json:"device_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListMaintenanceByDevice(ctx context.Context, arg ListMaintenanceByDeviceParams) ([]MaintenanceEvent, error) {
	rows, err := q.db.Query(ctx, listMaintenanceByDevice, arg.DeviceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceEvent
	for rows.Next() {
		var i MaintenanceEvent
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.At,
			&i.Interval,
			&i.Notes,
			&i.PerformedBy,
			&i.Cost,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
