// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID         int64              `json:"id"`
	DeviceID   int64              `json:"device_id"`
	Type       string             `json:"type"`
	Message    string             `json:"message"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Resolved   bool               `json:"resolved"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy *string            `json:"resolved_by"`
}

type Device struct {
	ID                       int64              `json:"id"`
	SerialNumber             string             `json:"serial_number"`
	Name                     string             `json:"name"`
	Model                    *string            `json:"model"`
	Manufacturer             *string            `json:"manufacturer"`
	YearOfManufacture        *int32             `json:"year_of_manufacture"`
	CommissionDate           pgtype.Date        `json:"commission_date"`
	TotalWorkingHour         *int32             `json:"total_working_hour"`
	AfterOverhaulWorkingHour *int32             `json:"after_overhaul_working_hour"`
	LastServiceAt            pgtype.Timestamptz `json:"last_service_at"`
	Location                 *string            `json:"location"`
	AvgDailyHours            *float64           `json:"avg_daily_hours"`
	ExpectedNextMaint        pgtype.Timestamptz `json:"expected_next_maint"`
	Status                   string             `json:"status"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
	CreatedBy                *string            `json:"created_by"`
	UpdatedBy                *string            `json:"updated_by"`
	DeletedBy                *string            `json:"deleted_by"`
	PlanID                   *int64             `json:"plan_id"`
}

type MaintenanceEvent struct {
	ID          int64              `json:"id"`
	DeviceID    int64              `json:"device_id"`
	At          pgtype.Timestamptz `json:"at"`
	Interval    *int32             `json:"interval"`
	Notes       *string            `json:"notes"`
	PerformedBy *string            `json:"performed_by"`
	Cost        pgtype.Numeric     `json:"cost"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Plan struct {
	ID            int64              `json:"id"`
	Name          string             `json:"name"`
	IntervalHours int32              `json:"interval_hours"`
	Description   *string            `json:"description"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Reading struct {
	ID         int64              `json:"id"`
	DeviceID   int64              `json:"device_id"`
	At         pgtype.Timestamptz `json:"at"`
	HoursDelta int32              `json:"hours_delta"`
	Location   *string            `json:"location"`
	OperatorID *string            `json:"operator_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
