CREATE TABLE IF NOT EXISTS plans (
  device_id BIGINT PRIMARY KEY REFERENCES devices(id) ON DELETE CASCADE,
  threshold_min DOUBLE PRECISION NOT NULL,
  threshold_max DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
