
services:
  db:
    image: postgres:16
    container_name: wh-ma-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Vietanh4791
      POSTGRES_DB: main-1
    ports:
      - "5432:5432"   # nếu 5432 bận, đổi bên trái thành 5433
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U admin -d main-1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - dbdata:/var/lib/postgresql/data
  sqlc:
    image: golang:1.22
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: ["/bin/sh","-lc"]
    command: >
      go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.27.0 &&
      /go/bin/sqlc generate

  migrate:
    image: migrate/migrate:latest
    container_name: wh-ma-migrate
    depends_on:
      db:
        condition: service_healthy
    # Dùng biến kết nối trực tiếp, trỏ tới service db trong compose
    environment:
      DATABASE_URL: postgres://admin:Vietanh4791@db:5432/main-1?sslmode=disable
    volumes:
      - ./db/migrations:/migrations
    # Giữ container ở trạng thái chờ; ta sẽ gọi lệnh one-off để chạy migrate

volumes:
  dbdata: {}
