name: wh-ma

services:
  db:
    image: postgres:16
    container_name: wh-ma-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Vietanh4791
      POSTGRES_DB: main-1
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d \"main-1\""]
      interval: 10s
      timeout: 5s
      retries: 10

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.118.0
    container_name: wh-ma-otel-collector
    command: ["--config=/etc/otelcol/otel-collector-config.yaml"]
    volumes:
      - ./configs/otel-collector-config.yaml:/etc/otelcol/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
      - "13133:13133"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8889/metrics >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 12

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: wh-ma-prometheus
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./configs/alerts.rules.yml:/etc/prometheus/alerts.rules.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:9090/-/ready >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 12

  grafana:
    image: grafana/grafana:10.4.3
    container_name: wh-ma-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/api/health >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 12

  jaeger:
    image: jaegertracing/all-in-one:1.60
    container_name: wh-ma-jaeger
    ports:
      - "16686:16686" # UI
      - "14250:14250" # gRPC collector
      - "14268:14268" # HTTP collector  
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:16686 >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 12

  migrate:
    image: migrate/migrate:v4.16.2
    volumes:
      - ./db/migrations:/migrations:ro
    env_file:
      - ./configs/.env
    # ENTRYPOINT của image đã là "migrate", nên chỉ cần truyền command (args)
    command: [
      "-path", "/migrations",
      "-database", "${DATABASE_URL}",
      "-verbose", "up"
    ]
    depends_on:
      db:
        condition: service_healthy
    restart: "no"


  api:
    build:
      context: .
      dockerfile: build/Dockerfile
    container_name: wh-ma-api
    env_file:
      - ./configs/.env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy    # ✅ khác so với file cũ: chờ DB healthy
      otel-collector:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/healthz >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 12

volumes:
  db_data: