services:
  db:
    image: postgres:16
    container_name: wh-ma-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Vietanh4791
      POSTGRES_DB: main-1
    ports: ["5432:5432"]   # nếu 5432 bận, đổi bên trái thành 5433
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U admin -d main-1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: {}
