// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: devices.sql

package db

import (
	"context"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateDevice(ctx context.Context, name string) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice, name)
	var i Device
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, name, created_at FROM devices WHERE id = $1
`

func (q *Queries) GetDevice(ctx context.Context, id int64) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
