// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID         int64
	DeviceID   int64
	ReadingID  pgtype.Int8
	Level      string
	Message    pgtype.Text
	IsServiced bool
	CreatedAt  pgtype.Timestamptz
	ServicedAt pgtype.Timestamptz
}

type Device struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Plan struct {
	DeviceID     int64
	ThresholdMin float64
	ThresholdMax float64
	CreatedAt    pgtype.Timestamptz
}

type Reading struct {
	ID       int64
	DeviceID int64
	Value    float64
	At       pgtype.Timestamptz
}
