groups:
- name: wh-ma
  rules:
  - alert: APIHighLatencyP95
    expr: histogram_quantile(
            0.95,
            sum by (le, path) (rate(http_request_duration_seconds_bucket[5m]))
          ) > 0.5
    for: 5m
    labels: { severity: warning }
    annotations:
      summary: "p95 > 500ms on {{ $labels.path }}"

  - alert: APIErrorRate
    expr: (sum(rate(http_requests_total{status=~"5..|4.."}[5m])) /
           sum(rate(http_requests_total[5m]))) > 0.02
    for: 5m
    labels: { severity: warning }
