receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  # ✅ SỬA: jaeger-all-in-one → jaeger (theo service name trong compose)
  otlphttp:
    endpoint: http://jaeger:4318
    
  prometheus:
    endpoint: 0.0.0.0:8889
    
  debug:
    verbosity: detailed

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888
      
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]