global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
  - job_name: 'otel-collector-telemetry'
    static_configs:
      - targets: ['otel-collector:8888']

rule_files:
  - "/etc/prometheus/alerts.rules.yml"