name: ci
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: Vietanh4791
          POSTGRES_DB: main-1
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U admin -d main-1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      DATABASE_URL: postgres://admin:Vietanh4791@localhost:5432/main-1?sslmode=disable

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install tools
        run: |
          go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
          go install github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Generate (sqlc)
        run: sqlc generate

      - name: Build & Vet & Test
        run: |
          go vet ./...
          go build ./...
          go test ./...

      - name: Wait for Postgres
        shell: bash
        run: |
          for i in {1..30}; do
            (echo > /dev/tcp/localhost/5432) >/dev/null 2>&1 && exit 0
            sleep 2
          done
          echo "Postgres not ready" && exit 1

      - name: Migrate up & down (dry-run on ephemeral DB)
        run: |
          migrate -path db/migrations -database "$DATABASE_URL" up
          migrate -path db/migrations -database "$DATABASE_URL" down
